name: Build

on:
  # workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-26.04-arm
    permissions:
      contents: read
      pull-requests: write
    env:
      RUSTFLAGS: -Dwarnings -Ctarget-feature=+simd128,+bulk-memory,+mutable-globals
    steps:
      - uses: actions/checkout@v7

      - uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: supplypike/setup-bin@v5
        with:
          uri: "https://github.com/WebAssembly/binaryen/releases/download/version_130/binaryen-version_130-aarch64-linux.tar.gz"
          name: "wasm-opt"
          version: "130"
          subPath: "binaryen-version_130/bin"

      - uses: taiki-e/install-action@v2.87.10
        with:
          tool: wasm-bindgen
      - run: |
          rustup default nightly
          rustup target add wasm32-unknown-unknown
          rustup component add rust-src --toolchain nightly-aarch64-unknown-linux-gnu

      - name: Set up Fastly CLI
        uses: fastly/compute-actions/setup@v14
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          version: 11
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - run: |
          cargo +nightly build --release --target wasm32-unknown-unknown --no-default-features -F png -Z build-std=panic_abort,std
          wasm-bindgen ./target/wasm32-unknown-unknown/release/bitmap_to_png.wasm --out-dir ./pkg --typescript --target web
          wasm-opt ./pkg/bitmap_to_png_bg.wasm -o ./pkg/bitmap_to_png_bg.wasm -Oz --dce --enable-simd --enable-bulk-memory --enable-nontrapping-float-to-int --enable-mutable-globals
      - run: node --run build
      - uses: actions/upload-artifact@v7
        with:
          name: wasm
          path: pkg/
          compression-level: 9
      - uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist/
          compression-level: 9
      - uses: preactjs/compressed-size-action@v3
        with:
          install-script: pnpm ci
          build-script: node --run build
          strip-hash: "-(\\w{8})\\."
      - name: Deploy
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'

      - run: |
          node --run fastly:deploy
          node --run fastly:publish
        working-directory: compute-js
        env:
          FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
